### ISSUE TITLE
Prueba de examen AZ-900

### ISSUE THREAD

**Issue by uriel5alazar** [josejesusguzman/acordeon-az900-innovaccion#1]
En el link que dirige a https://kahoot.it/challenge/02060231?challenge-id=17c998c7-d2ca-4aad-8555-25d087dca7da_1613089581619
Dice que ya alcanzo el máximo numero de jugadores

**Comment by josejesusguzman** [comment]
@uriel5alazar Ya se encuentra activo de nuevo, ya puedes hacer el examen
