### ISSUE TITLE
Error en la palabra ortografía

### ISSUE THREAD

**Issue by migarcia28** [josejesusguzman/acordeon-az900-innovaccion#2]
Hola, Sherpa esta mal escrito la palabra ortografía, al final de la página.

![image](https://user-images.githubusercontent.com/2805228/109756348-6476d480-7bad-11eb-8085-43243a050977.png)

**Comment by josejesusguzman** [comment]
Hola @migarcia28  si encuentras más errores así por favor siéntete libre de hacer un [Pull Request](https://styde.net/pull-request-en-github/)
