### ISSUE TITLE
Eror en los links de examenes 

### ISSUE THREAD

**Issue by FrancoEEspinozaF** [josejesusguzman/acordeon-az900-innovaccion#3]
Hola, sherpa al revisar el contenido me eh encontrado con que los links manda error y no se visualiza el contenido le paso a continuación el nombre de los links que no funcionan:
*Examen sobre el eje de Arquitectura de Soluciones
*Examen sobre cómo seleccionar las herramientas de tu solución
*Asignador al azar de casos tipo examen
Gracias por su tiempo y dedicación se  ve que lo hace con mucho cariño.

**Comment by josejesusguzman** [comment]
Hola @FrancoEEspinozaF  los acabo de subir. Ya están listos todos los examenes excepto el asignador al azar.
